src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Interests__c</fullName>
        <label>Interests</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Language__c</fullName>
        <label>Primary Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Completeness__c</fullName>
        <label>Profile Completeness</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User_Address__c.object
<CustomObject>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>AddressLine1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Address</label>
    <nameField>
        <displayFormat>Add-{0000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Address</pluralLabel>
    <recordTypes>
        <fullName>Additional_Location</fullName>
        <active>true</active>
        <label>Additional Location</label>
    </recordTypes>
    <recordTypes>
        <fullName>Primary_Location</fullName>
        <active>true</active>
        <label>Primary Location</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Position__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Position</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Position</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_InboundCreateUpdateUserWebService.cls
@isTest
public class Test_InboundCreateUpdateUserWebService {
    public static testMethod void testinboundService(){
        Test.startTest();
         User u = new User(Alias = 'testUser', Email= 'abc@xyde.com', 
              EmailEncodingKey='UTF-8', LastName= 'lstName', LanguageLocaleKey='en_US', 
              LocaleSidKey='en_US', ProfileId = GetProfile('System Administrator').ID, 
              TimeZoneSidKey='America/Los_Angeles', UserName='abc@xyde.com');
        u.Interests__c='abc;yze';
        u.Speciality__c='ade;dew';
        u.Primary_Language__c='English';
        u.Profile_Completeness__c='20';
        insert u;
        InboundCreateUpdateUserWebService inb= new InboundCreateUpdateUserWebService();
        InboundCreateUpdateUserWebService.cls_OperationMode Oper= new InboundCreateUpdateUserWebService.cls_OperationMode();
        Oper.op='Create';
        //test for create user
        InboundCreateUpdateUserWebService.userinfo us= new InboundCreateUpdateUserWebService.userinfo();
        InboundCreateUpdateUserWebService.userDetails userdet= new InboundCreateUpdateUserWebService.userDetails();
        InboundCreateUpdateUserWebService.primaryLocation primaryloc= new InboundCreateUpdateUserWebService.primaryLocation();
        primaryloc.phone='3333';
        InboundCreateUpdateUserWebService.addtionalLocations additonalloc= new InboundCreateUpdateUserWebService.addtionalLocations ();
        additonalloc.phone='282';
        List<InboundCreateUpdateUserWebService.addtionalLocations>listadditionalLoc= new List<InboundCreateUpdateUserWebService.addtionalLocations>();
        listadditionalLoc.add(additonalloc);
        InboundCreateUpdateUserWebService.position pos= new InboundCreateUpdateUserWebService.position();
        pos.title='abc';
        InboundCreateUpdateUserWebService.Company poscompany= new InboundCreateUpdateUserWebService.Company();
        poscompany.name='test';
        pos.company=poscompany;
        List<InboundCreateUpdateUserWebService.position>positonList= new List<InboundCreateUpdateUserWebService.position>();
        positonList.add(pos);
        userdet.positions=positonList;
        userdet.addtionalLocations=listadditionalLoc;
        userdet.primaryLocation=primaryloc;
        userdet.firstName='aceg@xyzom'+System.now();
        userdet.lastName='ade'+System.now();
        userdet.email='xob'+'@xy.com';
        userdet.userId='xob'+'@xy.com';
        //creating speciality data
        List<String> specialityDta= new List<String>();
        specialityDta.add('test');
        userdet.speciality=specialityDta;
        userdet.interests=specialityDta;
        userdet.hospitals=specialityDta;
        userdet.profileCompleteness=String.valueof(20.0);
        userdet.newsLetterFlag=String.valueof(true);
        us.ud=userdet;
        us.OperationMode=Oper;
        
        InboundCreateUpdateUserWebService.createUpdateUser(us);
        //test for update user
        Oper.op='Update';
        us.OperationMode=Oper;
        userdet.middleName='ac';
        userdet.maidenName='test';
        userdet.formattedName='test';
        userdet.phoneticFirstName='test';
        userdet.phoneticLastName='test';
        userdet.gender='male';
        userdet.professionalId='id';
        userdet.headLine='test';
        userdet.credentials='test';
        userdet.specialityDetails='test';
        userdet.medicalSchool='test';
        userdet.industry='industry';
        userdet.linkedInSpecialties='linkedInSpecialties';
        userdet.pictureUrl='pictureUrl';
        userdet.originalPictureUrl='originalPictureUrl';
        userdet.verified='verified';
        userdet.npi='npi';
        userdet.graduationYear='graduationYear';
        userdet.practiceType='practiceType';
        userdet.valueAmount='valueAmount';
        us.ud=userdet;
        InboundCreateUpdateUserWebService.createUpdateUser(us);
        Oper.op='Delete';
        us.OperationMode=Oper;
        InboundCreateUpdateUserWebService.createUpdateUser(us);
        RecordType rdPrimary=[Select id, DeveloperName from RecordType where DeveloperName='Primary_Location' Limit 1];
        User_Address__c ud = new User_Address__c();
        ud.AddressLine1__c='test';
        ud.RecordTypeId=rdPrimary.Id;
        ud.User__c=u.Id;
        insert ud;
        RecordType rdAdditionalLoc=[Select id, DeveloperName from RecordType where DeveloperName='Additional_Location' Limit 1];
        User_Address__c udadditional = new User_Address__c();
        udadditional.AddressLine1__c='test';
        udadditional.RecordTypeId=rdAdditionalLoc.Id;
        udadditional.User__c=u.Id;
        insert udadditional;
        User_Position__c up = new User_Position__c();
        up.Name='Test';
        up.User__c=u.Id;
        insert up;
   
        InboundFetchUserWebservice.readUserDetails('abc@xyde.com');
        InboundValidateUserWebService.validateUser('abc@xyde.com',null);
        InboundValidateUserWebService.validateUser(null,'abc@xyde.com');
       	Test.stopTest();
    }
     public static Profile GetProfile(String profileName) {
         Profile p = [SELECT Id FROM Profile WHERE Name =:profileName Limit 1];  
         return p;         
    }
    
}