src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ITG_Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITG_Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newsletter_Flag__c</fullName>
        <label>Newsletter Flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Provider__c</fullName>
        <label>Service Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/InboundValidateUserWebService.cls
@RestResource(urlMapping='/user_validate_AEM/*')
global class InboundValidateUserWebService {
    @HttpPost
    global static Boolean validateUser(String email, String userName){
        Boolean flag=false;
         if(email !=null){
            List<User> userList= [Select firstName, userName,lastName,email,country,ITG_Country__c,ITG_Region__c,Newsletter_Flag__c,Service_Provider__c from User where Email=:email];
            if(!userList.isEmpty()){
                flag=true;
            }
        }else if(userName!=null){
             List<User> userListUserName= [Select firstName, lastName,email,country,ITG_Country__c,ITG_Region__c,Newsletter_Flag__c,Service_Provider__c from User where userName=:userName];   
                if(!userListUserName.isEmpty()){
                flag=true;
            }
            }
        
        return flag;
    }

}